version: '3.7'

services:

  webserver:
    build:
      context: .
      args:
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_DRIVER_CLASS=${DB_DRIVER_CLASS}
        - DB_DRIVER=${DB_DRIVER}
        - DB_URL=${DB_URL}
    # open ports for tomcat and remote debugging
    ports:
      - "8080:8080"
      - "8000:8000"
    restart: always
